---
- name: test
  hosts: all
  remote_user: user
  gather_facts: false
  become: yes

  vars:
    vms:
      master:
        name: master.example.com
        ipaddress: 192.168.1.76/24
        vmid: 104
      slave:
        name: slave.example.com
        ipaddress: 10.21.21.52/24
        vmid: 201
  tasks:
    # with predefined vars
    - name: Print phone records "{{ inventory_hostname }}"
      debug:
        #msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.ipaddress }})"
        msg: the servers is {{ inventory_hostname }}.ba.ru 
      #loop: "{{ lookup('dict', vms) }}"