api_host: xxxx 
api_user: xxxxx
api_password: xxxx
node: xxxxx
clone_vm: xxxxxx
key_name: id_rsa.pub
vms:
  master:
    name: master
    ipaddress: 192.168.1.76/24
    vmid: 104
    cores: 1
    sockets: 1
    memory: 1024
  slave:
    name: slave
    ipaddress: 10.21.21.52/24
    vmid: 201
    cores: 4
    sockets: 1
    memory: 16384